# Generated by Django 4.0.4 on 2022-05-08 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_total_alter_project_id_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4001e66-c193-4288-b866-be5113cff0f1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b28b55b-15e6-4167-9d1d-ddef121b1a89'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fbd27922-48c2-47c8-8170-65cb704af58a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
