# Generated by Django 4.0.4 on 2022-05-08 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d3c35c5-0b71-427e-9668-9d145bebbb81'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f198bc8-ccc0-498e-a3e0-8742d9d137e4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('Up', 'Up Vote'), ('Down', 'Down Vote')], max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f0ce638a-1cd8-4b95-8f76-a53cbef78f17'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
