# Generated by Django 4.0.4 on 2022-05-08 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_id_alter_review_id_alter_review_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc205732-4851-4427-a1bd-895499089f93'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dfc8ec97-87e8-4c4f-a324-aa4bd9555fbb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbcfafe8-651a-4d6e-aacc-54983eeee107'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
