# Generated by Django 4.0.4 on 2022-05-11 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_id_alter_review_body_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a24daef-263a-4dfb-9369-2f4ebec97b25'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4ea279b-b1d7-41bc-a481-3746bb6c4c9b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d86da122-e986-4474-90e1-cdc7a456407d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
