# Generated by Django 4.0.4 on 2022-05-13 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c273889-338c-455d-a8ed-ede601863acd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('408ac358-5eaa-41f4-97ac-f3ff6a703e49'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2665e4fb-9e55-4993-8208-8c676bf8d070'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
