# Generated by Django 4.0.4 on 2022-05-18 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_id_alter_review_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b12d96e-9c11-4cc9-b05d-69bf3e456a40'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f41a5395-3e9f-4efc-a459-78996bc03ab2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e2bb9cb-2af6-4604-8636-9a3b66d27c65'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
